releases:
  - name: Llama Stack
    version: v0.3.0rc2+rhai0
    repoUrl: https://github.com/opendatahub-io/llama-stack
  - name: Llama Stack Operator
    version: v0.4.0
    repoUrl: https://github.com/opendatahub-io/llama-stack-k8s-operator
